language: erlang
script: "make test"
otp_release:
  - 22.0
  - 21.2
  - 21.0
  - 20.0
  - 19.0
  - 18.0
  - 17.4
  - 17.0
  - R16B
  - R15B03
before_script: "sudo apt-get --yes --force-yes install libpam-runtime python-software-properties"
